# Generated by Django 4.0.2 on 2022-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', 'рубли'), ('EUR', 'евро'), ('USD', 'доллар'), ('USD1', 'доллар1')], max_length=32, verbose_name='Валюта'),
        ),
    ]
